using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._ES.Stagehand.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESStagehandJoinWindow : FancyWindow
{
    public event Action? OnAcceptButtonPressed;

    public ESStagehandJoinWindow()
    {
        RobustXamlLoader.Load(this);

        AcceptButton.OnPressed += _ => OnAcceptButtonPressed?.Invoke();
        DenyButton.OnPressed += _ => Close();
    }
}
