using Content.Client.Stylesheets;
using Content.Shared._ES.Voting;
using Content.Shared._ES.Voting.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._ES.Voting.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESVoteControl : PanelContainer
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action<Entity<ESVoteComponent>, ESVoteOption>? OnVoteChanged;

    public EntityUid Vote { get; init; } = EntityUid.Invalid;

    private TimeSpan _endTime;

    public ESVoteControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void Update(Entity<ESVoteComponent> vote, EntityUid owner)
    {
        if (!_entityManager.EntityExists(vote))
            return;

        var netOwner = _entityManager.GetNetEntity(owner);

        Progress.MinValue = (float) (vote.Comp.EndTime - vote.Comp.Duration).TotalSeconds;
        Progress.MaxValue = (float)vote.Comp.EndTime.TotalSeconds;
        _endTime = vote.Comp.EndTime;

        var name = _entityManager.GetComponentOrNull<MetaDataComponent>(vote)?.EntityName ?? string.Empty;
        VoteNameLabel.Text = Loc.GetString("es-voter-ui-header-text-format", ("title", name));

        var group = new ButtonGroup();

        if (OptionsContainer.ChildCount == 0)
        {
            foreach (var (option, votes) in vote.Comp.Votes)
            {
                var button = new ESVoteButton
                {
                    Group = group,
                    Option = option,
                    HorizontalExpand = true,
                    Pressed = votes.Contains(netOwner),
                };

                button.OnPressed += _ =>
                {
                    OnVoteChanged?.Invoke(vote, option);
                };

                OptionsContainer.AddChild(button);
            }
            OptionsContainer.InvalidateArrange();
        }

        foreach (var child in OptionsContainer.Children)
        {
            if (child is ESVoteButton voteButton)
            {
                var votes = vote.Comp.Votes.GetValueOrDefault(voteButton.Option) ?? [];
                if (vote.Comp.ShowCount)
                {
                    voteButton.Label.Text = Loc.GetString("es-voter-ui-button-text-option-format",
                        ("option", voteButton.Option.DisplayString),
                        ("count", votes.Count));
                }
                else
                {
                    voteButton.Label.Text = Loc.GetString("es-voter-ui-button-text-option-format-no-count",
                        ("option", voteButton.Option.DisplayString));
                }
            }
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;

        TimeLabel.Text = $"{_endTime - curTime:mm\\:ss}";
        Progress.Value = (float) curTime.TotalSeconds;
    }

    private sealed class ESVoteButton : ContainerButton
    {
        public RichTextLabel Label { get; }
        public ESVoteOption Option { get; set; } = default!;

        public ESVoteButton()
        {
            StyleClasses.Add(StyleClassButton);
            StyleClasses.Add(StyleBase.ButtonOpenBoth);
            ToggleMode = true;

            Label = new RichTextLabel();
            AddChild(Label);
        }
    }
}
